import type {Metadata} from "next"
import "@/style/globals.css"
import React from "react"
import {Abril_Fatface, DM_Sans, Open_Sans} from "next/font/google"
import Card from "@/component/card"
import "@/style/gradient.css"

const openSans = Open_Sans({
	variable: "--font-open-sans",
	subsets: ["latin"],
})

const fatFace = Abril_Fatface({
	variable: "--font-abril-fatface",
	subsets: ["latin"],
	weight: "400"
})

const dmSans = DM_Sans({
	variable: "--font-dm-sans",
	subsets: ["latin"]
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
	const NavButtons = ({href, text}: {href: string, text: string}) => (
		<li><a href={href} className={"hover:bg-black/5 hover:shadow-lg p-2 rounded-2xl underline underline-offset-2 transition"}>{text}</a></li>
	)

	return (
		<html lang="da">
			<body className={`${openSans.variable} ${openSans.className} ${fatFace.variable} ${dmSans.variable} antialiased main_page__background`}>
				<header className={"sticky top-0 z-50 wrapper"}>
					<nav className={"flex gap-4 justify-between items-center p-4"}>
						<a href="/" className={"w-full max-w-100 shadow-lg hover:shadow-xl hover:scale-105 transition"}><img src="/ilaere.dk-logo.png" alt="ilære.dk logo"/></a>
						<Card>
							<ul className={"hidden xl:flex gap-2 justify-center items-center h-full p-6 whitespace-nowrap"}>
								<NavButtons href={"#"} text={"Mød virksomhederne"}/>
								<NavButtons href={"#"} text={"Erhvervsuddannelser"}/>
								<NavButtons href={"#"} text={"Info"}/>
								<NavButtons href={"#"} text={"Kontakt"}/>
								<NavButtons href={"#"} text={"Bliv en del af ilære.dk"}/>
							</ul>
						</Card>
					</nav>
				</header>
				{children}
				<footer>

				</footer>
			</body>
		</html>
	)
}
